repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports, --follow-imports=silent]
      additional_dependencies: [importlib_resources, pytest, types_tzlocal]
