name: Test miyadaiku

on:
  push:

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create venv
        run: |
          python3 -m venv .venv

      - name: Install dependencies
        run: |
          .venv/bin/pip3 install -e .\[dev\]

      - name: Test
        run: |
          .venv/bin/pytest
